### ISSUE TITLE
Phone Wake Up

### ISSUE THREAD

**Issue by zeeshanjan82** [Viras-/cordova-plugin-powermanagement#10]
I have successfully integrated the plugin in my cordova app and am able to capture the acquire and release events but the issue I am facing is this. When I acquire the wakelock my phone is not active , its locked but the app is running so when from another phone I try to send the socket.io event , the acquire even is called but the phone does not wake up. How can I make sure that the phone wakes up when the acquire event is fired.

**Comment by Viras-** [comment]
not sure if it is possible to "turn on" the device while the screen is locked. This plugin is intended to prevent locking of the device beforehand.
AFAIK there is no way to unlock / turn on the device without user interaction.

**Comment by zeeshanjan82** [comment]
Thanks @Viras- what I am looking for is exactly the feature which is in skype of any calling app where when the phone is locked or in sleep mode, the user is able to respond to the call. I do not want the app to unlock the phone but show a screen like skype or whatsapp does during calling.

**Comment by Viras-** [comment]
hey - to be honest I have no idea if this is possible without any special modifications (remember: skype is a microsoft internal app). Of course you can always use something like PushNotifications to let the user know that something new is happening in your app.

**Comment by zeeshanjan82** [comment]
I have couple of other apps which do the same like WhatsApp when we have call in WhatsApp , we can receive the call or decline it even when the phone is locked or it gets awake when the call comes. Also I have found in some free alarm applications which are available on android the same behavior available , the alarm screen is made available even when the app is locked or in sleep mode.

**Comment by Viras-** [comment]
I see - still I think this is out of the scope of this plugin.

The idea behind this plugin is to keep the device awake even without user intervention. I guess for your problem you would have to create a new plugin?!

**Comment by hipertrix** [comment]
I have similar problem. Need to open my app but the device is locked.
