### ISSUE TITLE
Question: is it also possible to keep WIFI always on with this plugin?

### ISSUE THREAD

**Issue by amunters** [Viras-/cordova-plugin-powermanagement#16]
Hi, 
on some devices the WIFI is stopped after some time of inactivity.
My app fetches data periodically from a server so it is important to keep the connection alive.
Would it be possible to use this plugin to keep the WIFI 'wakelocked' so that the connection will be kept alive at all times?

**Comment by bassena** [comment]
You can usually set WIFI to always be connected when the device is asleep in the device's WIFI settings.

**Comment by Viras-** [comment]
No the purpose of this plubin is to keep the devices screen turned on.
