### ISSUE TITLE
Please write a doc !

### ISSUE THREAD

**Issue by Cocorico01** [Viras-/cordova-plugin-powermanagement#3]
Hi,
Can you write a doc please, because I dont know how to use it.
Thanks 

Coco

**Comment by PeterUstinox** [comment]
no, it is window.powerManagement.acquire() und window.powerManagement.release().
The methods you mentioned come from [this repo](https://github.com/aharris88/phonegap-powerManagement-plugin/).

**Comment by Viras-** [comment]
There is a usage part in the readme now thanks to @Menardi ! In addition it is now possible to configure the onPause behaviour!
