### ISSUE TITLE
Screen dims after 3 minutes on android (Samsung Galaxy S9)

### ISSUE THREAD

**Issue by AndersBillLinden** [Viras-/cordova-plugin-powermanagement#31]
I installed the plugin with

````
cordova plugin add cordova-plugin-powermanagement
````

I added this to my code:

````
    document.addEventListener("deviceready", onDeviceReady, false);

    function onDeviceReady() {
        window.powerManagement.acquire(function(){}, function(){});
    }
````

When running this app, the screen dims after 3 minutes.

**Comment by karol-glomski** [comment]
Maybe you are getting an error and you don't know about it? I would log success/error and be sure that the plugin itself works properly.
