### ISSUE TITLE
Issue : ClassNotFound Exception

### ISSUE THREAD

**Issue by Cocorico01** [Viras-/cordova-plugin-powermanagement#4]
If I add "
        <script type="text/javascript" charset="utf-8" src="js/powermanagement.js"></script>
"
 I can call PowerManager.prototype.acquire(success, fail, false)
But fail(error) was called and alert(error) says "ClassNotFoundException".

If i dont add this, with this code : 
 try {
        alert(window.plugin);
      PowerManagement.prototype.acquire(successWakeAcquired, errorWakeAcquired, false);
    }
    catch (e) {
        alert(e);
    }

I have this : "ReferenceError: PowerManager is not defined.
What's the problem ? please make a tuto/doc ?
thanks

Coco

**Comment by Viras-** [comment]
Checkout the usage section in the readme!
