### ISSUE TITLE
Corrected Issue on Android

### ISSUE THREAD

**Issue by GeeMatt** [Viras-/cordova-plugin-powermanagement#6]
My app was crashing when switching to a new app. The correction was found in this StackOverflow: http://stackoverflow.com/questions/12140844/java-lang-runtimeexception-wakelock-under-locked-c2dm-lib

I corrected it locally and the crash went away. I opted to just put the try/catch around the release() method. You may want to update the code for this issue.

Thanks for the great plugin.

**Comment by Menardi** [comment]
I've submitted a pull request with this fix.

This error was happening quite frequently with my app, which is a timer for running. What happened was the screen would turn off, firing the onPause handler. This would call release directly on the wakelock. Then the user's running exercise would end, and I release the wakelock. Thus the count is 1 acquire, 2 releases, and the wakelock is underlocked, causing the crash.

The quickest fix for this is the try / catch like you described, which I've included in my PR. I may update it with a cleaner fix but it works for now.
