### ISSUE TITLE
iOS powerManagement.dim

### ISSUE THREAD

**Issue by tinnocente** [Viras-/cordova-plugin-powermanagement#9]
Is the Partial Wake Lock (dim only) supposed to work on iOS?  It acquires the lock but the screen never diims.  The full wake lock works perfectly.  Am I doing something wrong?

Thanks

**Comment by Viras-** [comment]
No - on iOS the partial wake lock is the same as the full wake lock. AFAIK there is no possibility under iOS to allow dimming the screen.

**Comment by Kaushik0704** [comment]
@tinnocente @Viras- How to use this plugin for iOS..?
